### ISSUE TITLE
Failing Github release assets upload action

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_wave#3]
This library has failed the last several github release upload actions. https://github.com/adafruit/Adafruit_CircuitPython_Wave/actions/runs/7152684527/job/19478284375
```
Error: Error: unexpected status code: 403
```

**Comment by jepler** [comment]
Speculatively changing a setting and re-running ... did a github default change or did was a step missed creating this repo?
![image](https://github.com/adafruit/Adafruit_CircuitPython_Wave/assets/1517291/2e29d89f-df53-4ae7-8ce3-1286922432a1)

**Comment by jepler** [comment]
That fixed it. I added an item to the FAQ of https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/releasing-on-github with the related error & solution.

**Comment by FoamyGuy** [comment]
Thank you!
